version: '2'

services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/tracker_api_dev
      PORT: 8000

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tracker_api_dev
      POSTGRES_HOST_AUTH_METHOD: trust
